data_preprocessing_soil:
  k_neighbors: 5
  threshold_m: 20000

data_preprocessing_seeds:
  lower_bound: 2

data_merging_climate:
  start_date: [2013, 1, 1]
  end_date: [2024, 12, 31]

data_cleaning_climate:
  threshold: 0.4
  method: 'linear'
  date_limit: '2024-06-30'

data_integration_climate:
  threshold_m: 20000 #20km radio

model_building:
  general_params:
    dim: 8
    time: 64
    stride: 3
  metric: "wassertein"
  params_list: [
        {"embedding_dimension": 8, "embedding_time_delay": 23, "epsilon": 0.08},   # Tmax
        {"embedding_dimension": 8, "embedding_time_delay": 23, "epsilon": 0.085},  # Tmin
        {"embedding_dimension": 12, "embedding_time_delay": 21, "epsilon": 0.05}   # Precip
        ]
  candidate: [0.157, 0.157,0.156, 0.53]
  device: "gpu"
  optimize:
    n_initial: 1000
    m_refine: 50
    refine_delay: 0.9
    seed: 42

