data_preprocessing_soil:
  k_neighbors: 5
  threshold_m: 20000

data_preprocessing_seeds:
  evaluation_metric: 'Rendimiento'
  list_generation_metric: 'Valorproduccion'
  lower_bound: 0.8

data_merging_climate:
  start_date: [2013, 1, 1]
  end_date: [2024, 12, 31]

data_cleaning_climate:
  threshold: 0.4
  method: 'linear'
  date_limit: '2024-06-30'
  average_n_days: 3

data_integration_climate:
  threshold_m: 20000 #20km radio

model_building:
  general_params:
    dim: 8
    time: 32
    stride: 1
  metric: "wasserstein"
  params_list: [
        {"embedding_dimension": 7, "embedding_time_delay": 28, "epsilon": 0.07},   # Tmax
        {"embedding_dimension": 7, "embedding_time_delay": 29, "epsilon": 0.075},  # Tmin
        {"embedding_dimension": 14, "embedding_time_delay": 33, "epsilon": 0.04}   # Precip
        ]
  candidate: [0.1, 0.15,0.4, 0.35]
  device: "gpu"
  optimize:
    n_initial: 2000
    m_refine: 30
    refine_delay: 0.9
    seed: 42
    parameters_type: 'fixed'


